In [2]:
import numpy as np
import torch
import tensorflow as tf

Mảng 1 chiều NumPy : [1 2 3 4 5] <class 'numpy.ndarray'>
Tensor PyTorch 1 chiều: tensor([1, 2, 3, 4, 5])
Tensor TensorFlow 1 chiều: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


## Day 14 - Transpose

### Câu 1

In [24]:
#Numpy
np.random.seed(2024)
arr_np1 = np.random.randint(-10,10, size =(3,4))
arr_np2 = np.random.randint(-10,10, size =(3,4))
arr_np2_transposed = arr_np2.T
np_matmul = np.matmul(arr_np1, arr_np2_transposed)

print('Mảng 1: \n', arr_np1)
print('Mảng 2: \n', arr_np2)
print('Mảng chuyển vị mảng 2: \n', arr_np2_transposed)
print('Nhân matrix multiplication: \n', np_matmul)

Mảng 1: 
 [[ -2 -10 -10  -6]
 [ -1  -9  -7   0]
 [ -8 -10  -5   7]]
Mảng 2: 
 [[ 5  0  4  5]
 [ 1 -3  8 -1]
 [-4  0 -9 -5]]
Mảng chuyển vị mảng 2: 
 [[ 5  1 -4]
 [ 0 -3  0]
 [ 4  8 -9]
 [ 5 -1 -5]]
Nhân matrix multiplication: 
 [[-80 -46 128]
 [-33 -30  67]
 [-25 -25  42]]


In [25]:
#Tensorflow

tf.random.set_seed(2024)

arr_tf1 = tf.random.uniform(shape=(3, 4), minval=-10, maxval=10, dtype=tf.int32)
arr_tf2 = tf.random.uniform(shape=(3, 4), minval=-10, maxval=10, dtype=tf.int32)
arr_tf2_transposed = tf.transpose(arr_tf2)
tf_matmul = tf.matmul(arr_tf1, arr_tf2_transposed)

print('Mảng 1: \n', arr_tf1)
print('Mảng 2: \n', arr_tf2)
print('Mảng chuyển vị mảng 2: \n', arr_tf2_transposed)
print('Nhân matrix multiplication: \n', tf_matmul)


Mảng 1: 
 tf.Tensor(
[[-6 -2  0 -2]
 [ 4  4 -9  3]
 [ 7  1  2 -5]], shape=(3, 4), dtype=int32)
Mảng 2: 
 tf.Tensor(
[[-3 -7  9  3]
 [ 2 -5 -3 -5]
 [ 4 -3 -3  5]], shape=(3, 4), dtype=int32)
Mảng chuyển vị mảng 2: 
 tf.Tensor(
[[-3  2  4]
 [-7 -5 -3]
 [ 9 -3 -3]
 [ 3 -5  5]], shape=(4, 3), dtype=int32)
Nhân matrix multiplication: 
 tf.Tensor(
[[  26    8  -28]
 [-112    0   46]
 [ -25   28   -6]], shape=(3, 3), dtype=int32)


In [29]:
#Pytorch
torch.manual_seed(2024)

arr_tensor1 = torch.randint(-10,10, size =(3,4))
arr_tensor2 = torch.randint(-10,10, size =(3,4))
arr_tensor2_transposed = arr_tensor2.T
tensor_matmul = torch.matmul(arr_tensor1, arr_tensor2_transposed)

print('Mảng 1: \n', arr_tensor1)
print('Mảng 2: \n', arr_tensor2)
print('Mảng chuyển vị mảng 2: \n', arr_tensor2_transposed)
print('Nhân matrix multiplication: \n', tensor_matmul)

Mảng 1: 
 tensor([[  2,   0,  -6, -10],
        [ -7, -10,   0,   1],
        [  3,   9,   7,  -6]])
Mảng 2: 
 tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]])
Mảng chuyển vị mảng 2: 
 tensor([[  1,  -9,  -3],
        [  8, -10,  -7],
        [  0,  -9,  -4],
        [ -2,   0,   8]])
Nhân matrix multiplication: 
 tensor([[  22,   36,  -62],
        [ -89,  163,   99],
        [  87, -180, -148]])


### Câu 2

In [32]:
# Numpy
np.random.seed(2024)
arr_np3 = np.random.randint(-10,10, size =(3,3))
total_np = np .sum(arr_np3)
total_np_col = np.sum(arr_np3, axis =0)
total_np_row = np.sum(arr_np3, axis =1)

print('Mảng: ', arr_np3)
print('Tổng: ', total_np)
print('Tổng cột: ', total_np_col)
print('Tổng dòng: ', total_np_row)

Mảng:  [[ -2 -10 -10]
 [ -6  -1  -9]
 [ -7   0  -8]]
Tổng:  -53
Tổng cột:  [-15 -11 -27]
Tổng dòng:  [-22 -16 -15]


In [37]:
#Tensorflow

tf.random.set_seed(2024)

arr_tf3 = tf.random.uniform(shape=(3, 3), minval=-10, maxval=10, dtype=tf.int32)

total_tf = tf.reduce_sum(arr_tf3)
total_tf_col = tf.reduce_sum(arr_tf3, axis =0)
total_tf_row = tf.reduce_sum(arr_tf3, axis =1)

print('Mảng: ', arr_tf3)
print('Tổng: ', total_tf)
print('Tổng cột: ', total_tf_col)
print('Tổng dòng: ', total_tf_row)

Mảng:  tf.Tensor(
[[-6 -2  0]
 [-2  4  4]
 [-9  3  7]], shape=(3, 3), dtype=int32)
Tổng:  tf.Tensor(-1, shape=(), dtype=int32)
Tổng cột:  tf.Tensor([-17   5  11], shape=(3,), dtype=int32)
Tổng dòng:  tf.Tensor([-8  6  1], shape=(3,), dtype=int32)


In [35]:
#Pytorch
torch.manual_seed(2024)

arr_tensor3 = torch.randint(-10,10, size =(3,3))

total_tensor = torch.sum(arr_tensor3)
total_tensor_col = torch.sum(arr_tensor3, axis =0)
total_tensor_row = torch.sum(arr_tensor3, axis =1)

print('Mảng: ', arr_tensor3)
print('Tổng: ', total_tensor)
print('Tổng cột: ', total_tensor_col)
print('Tổng dòng: ', total_tensor_row)

Mảng:  tensor([[  2,   0,  -6],
        [-10,  -7, -10],
        [  0,   1,   3]])
Tổng:  tensor(-27)
Tổng cột:  tensor([ -8,  -6, -13])
Tổng dòng:  tensor([ -4, -27,   4])
